### ISSUE TITLE
Write wiki about how to deploy it in Heroku

### ISSUE THREAD

**Issue by liginv** [liginv/kozhikoden#10]
The How-To of deployment in heroku. if someone clone the project how can they deploy this project under their name in heroku.

**Comment by alenthomas** [comment]
okay that can be arranged

**Comment by alenthomas** [comment]
done [wiki post](https://github.com/liginv/kozhikoden/wiki/Deploy-on-heroku).

Closing issue, check and re-open is anything is missing
